name: setup-golden-image-debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-20.04
    steps:      
      - uses: actions/checkout@v2

      - name: Packer build
        uses: enr0s/packer-qemu-action@v1.0
        with:
          templateFile: 'packer.pkr.hcl'
          workingDir: '.'
