name: setup-golden-image-debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2

      # Install qemu 
      - name: Set up QEMU
        run: sudo apt install --no-install-recommends qemu-system-x86
